exclude = ["turbo-sim.py"]
line-length = 88
target-version = "py310"

select = [
    # flake8-builtins
    "A",
    # flake8-bugbear
    "B",
    # isort
    "I001",
    "I002",
    # tidy imports
    "TID"
]
